from datetime import datetime, timezone

ALERTS = [
    {
        "alert_id": "alr_001",
        "fingerprint": "fp_leak_acmecorp",
        "source_id": "src_pastesite_x",
        "watchlist_id": "wl_credential_leaks",
        "severity": "critical",
        "confidence": 0.950,
        "state": "new",
        "first_seen": datetime(2026, 9, 20, 8, 15, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 9, 30, tzinfo=timezone.utc),
        "count": 1,
    },
    {
        "alert_id": "alr_002",
        "fingerprint": "fp_leak_acmecorp",  # duplicate of alr_001
        "source_id": "src_pastesite_y",
        "watchlist_id": "wl_credential_leaks",
        "severity": "critical",
        "confidence": 0.910,
        "state": "new",
        "first_seen": datetime(2026, 9, 21, 14, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 10, 5, tzinfo=timezone.utc),
        "count": 1,
    },
    {
        "alert_id": "alr_003",
        "fingerprint": "fp_leak_othercorp",
        "source_id": "src_pastesite_x",
        "watchlist_id": "wl_credential_leaks",
        "severity": "critical",
        "confidence": 0.880,
        "state": "new",
        "first_seen": datetime(2026, 9, 22, 6, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 6, 0, tzinfo=timezone.utc),
        "count": 1,
    },
    {
        "alert_id": "alr_004",
        "fingerprint": "fp_domain_impersonation_1",
        "source_id": "src_domainwatch",
        "watchlist_id": "wl_brand_protection",
        "severity": "high",
        "confidence": 0.820,
        "state": "new",
        "first_seen": datetime(2026, 9, 19, 11, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 8, 0, tzinfo=timezone.utc),
        "count": 2,
    },
    {
        "alert_id": "alr_005",
        "fingerprint": "fp_cve_mention_1",
        "source_id": "src_forumscrape",
        "watchlist_id": "wl_cve_watch",
        "severity": "high",
        "confidence": 0.747,
        "state": "new",
        "first_seen": datetime(2026, 9, 21, 3, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 21, 3, 0, tzinfo=timezone.utc),
        "count": 1,
    },
    {
        "alert_id": "alr_006",
        "fingerprint": "fp_exposed_api_key",
        "source_id": "src_githubscrape",
        "watchlist_id": "wl_secrets_exposure",
        "severity": "high",
        "confidence": 0.815,
        "state": "acknowledged",
        "first_seen": datetime(2026, 9, 18, 9, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 20, 12, 0, tzinfo=timezone.utc),
        "count": 5,
    },
    {
        "alert_id": "alr_007",
        "fingerprint": "fp_cve_mention_2",
        "source_id": "src_forumscrape",
        "watchlist_id": "wl_cve_watch",
        "severity": "medium",
        "confidence": 0.530,
        "state": "new",
        "first_seen": datetime(2026, 9, 22, 4, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 4, 0, tzinfo=timezone.utc),
        "count": 3,
    },
    {
        "alert_id": "alr_008",
        "fingerprint": "fp_brand_mention_1",
        "source_id": "src_socialscrape",
        "watchlist_id": "wl_brand_protection",
        "severity": "medium",
        "confidence": 0.743,
        "state": "investigating",
        "first_seen": datetime(2026, 9, 17, 10, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 21, 15, 0, tzinfo=timezone.utc),
        "count": 1,
    },
    {
        "alert_id": "alr_009",
        "fingerprint": "fp_typosquat_domain_1",
        "source_id": "src_domainwatch",
        "watchlist_id": "wl_brand_protection",
        "severity": "medium",
        "confidence": 0.792,
        "state": "new",
        "first_seen": datetime(2026, 9, 22, 1, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 7, 0, tzinfo=timezone.utc),
        "count": 5,
    },
    {
        "alert_id": "alr_010",
        "fingerprint": "fp_general_chatter_1",
        "source_id": "src_chatterfeed",
        "watchlist_id": "wl_general_monitoring",
        "severity": "low",
        "confidence": 0.619,
        "state": "new",
        "first_seen": datetime(2026, 9, 20, 5, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 2, 0, tzinfo=timezone.utc),
        "count": 4,
    },
    {
        "alert_id": "alr_011",
        "fingerprint": "fp_general_chatter_2",
        "source_id": "src_chatterfeed",
        "watchlist_id": "wl_general_monitoring",
        "severity": "low",
        "confidence": 0.853,
        "state": "resolved",
        "first_seen": datetime(2026, 9, 15, 8, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 16, 8, 0, tzinfo=timezone.utc),
        "count": 2,
    },
    {
        "alert_id": "alr_012",
        "fingerprint": "fp_brand_mention_2",
        "source_id": "src_socialscrape",
        "watchlist_id": "wl_brand_protection",
        "severity": "low",
        "confidence": 0.755,
        "state": "new",
        "first_seen": datetime(2026, 9, 21, 20, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 3, 0, tzinfo=timezone.utc),
        "count": 4,
    },
    {
        "alert_id": "alr_013",
        "fingerprint": "fp_industry_mention_1",
        "source_id": "src_chatterfeed",
        "watchlist_id": "wl_general_monitoring",
        "severity": "informational",
        "confidence": 0.977,
        "state": "new",
        "first_seen": datetime(2026, 9, 22, 0, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 0, 0, tzinfo=timezone.utc),
        "count": 5,
    },
    {
        "alert_id": "alr_014",
        "fingerprint": "fp_industry_mention_2",
        "source_id": "src_forumscrape",
        "watchlist_id": "wl_general_monitoring",
        "severity": "informational",
        "confidence": 0.664,
        "state": "false_positive",
        "first_seen": datetime(2026, 9, 19, 6, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 19, 6, 0, tzinfo=timezone.utc),
        "count": 2,
    },
    {
        "alert_id": "alr_015",
        "fingerprint": "fp_industry_mention_3",
        "source_id": "src_chatterfeed",
        "watchlist_id": "wl_general_monitoring",
        "severity": "informational",
        "confidence": 0.799,
        "state": "new",
        "first_seen": datetime(2026, 9, 20, 18, 0, tzinfo=timezone.utc),
        "last_seen": datetime(2026, 9, 22, 5, 0, tzinfo=timezone.utc),
        "count": 5,
    },
]
