"""create alerts table

Revision ID: 07e96f70de43
Revises: 86b26485af07
Create Date: 2026-09-25 06:22:54.974433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e96f70de43'
down_revision: Union[str, Sequence[str], None] = '86b26485af07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=100), nullable=False),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('watchlist_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_fingerprint'), 'alerts', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_fingerprint'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
