"""create audit event and webhook endpoint tables

Revision ID: 86b26485af07
Revises: 0da005daf846
Create Date: 2026-09-24 23:38:14.659799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '86b26485af07'
down_revision: Union[str, Sequence[str], None] = '0da005daf846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('actor_usr', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Text(), nullable=True),
    sa.Column('object_id', sa.Text(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=False),
    sa.Column('entry_hash', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('endpoint_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('hmac_secret', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_endpoint_id'), 'webhook_endpoints', ['endpoint_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_endpoints_endpoint_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
